name: faye_dart
description: Faye is a publish/subscribe messaging protocol that is built on the Bayeux protocol, a messaging system utilized for transporting asynchronous messages over HTTP.
version: 0.1.0
homepage: https://github.com/GetStream/stream-feed-flutter/blob/master/packages/faye_dart
repository: https://github.com/GetStream/stream-feed-flutter/blob/master/packages/faye_dart
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  web_socket_channel: ^2.1.0
  equatable: ^2.0.0
  logging: ^1.0.1
  uuid: ^3.0.4
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.3
  mocktail: ^0.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec