name: stream_feed
description: Stream Feed official Dart SDK. Build your own feed experience using Dart and Flutter. 
version: 0.4.0+1
repository: https://github.com/GetStream/stream-feed-flutter
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
homepage: https://getstream.io/
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  dio: ^4.0.0
  equatable: ^2.0.0
  faye_dart: ^0.1.0
  http_parser: ^4.0.0
  intl: ^0.17.0
  jose: ^0.3.2
  json_annotation: ^4.0.1
  logging: ^1.0.1
  meta: ^1.3.0
  mime: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.2
  json_serializable: ^4.1.1
  mocktail: ^0.1.2
  test: ^1.17.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
