name: stream_feed
description: Stream Feed official Dart SDK. Build your own feed experience using Dart and Flutter. 
version: 0.0.1
homepage: https://getstream.io/
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0-prev2
  equatable: ^2.0.0
  faye_dart: ^0.1.0
  jose: ^0.3.0-nullsafety.2
  json_annotation: ^4.0.0
  meta: ^1.3.0
  mime: ^1.0.0
  logging: ^1.0.1

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^4.0.2
  mocktail: ^0.1.0
  test: ^1.16.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
