name: stream_feed_flutter_core
description: Stream Feed official Flutter SDK Core. Build your own feed experience using Dart and Flutter.
version: 0.4.0
repository: https://github.com/GetStream/stream-feed-flutter
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
homepage: https://getstream.io/
environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.1
  stream_feed: ^0.4.0
  equatable: ^2.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.2
