name: stream_feed_flutter_core
description: Stream Feed official Flutter SDK Core. Build your own chat experience using Dart and Flutter.
version: 0.0.0
homepage: https://getstream.io/
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.1
  stream_feed:
    path: ../stream_feed

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.2
